### ISSUE TITLE
Kiln shows "Structure incomplete!", Could not load file or assembly VSSurvivalMod

### ISSUE THREAD

**Issue by FalcoGer** [zach2039/vs-beehivekiln#1]
When looking at the flue, the block info says "Structure incomplete" Firing progress is reset."

I have however constructed the kiln according to the images. When breaking a single block and sneak + RMB on the flue, it shows "1 block missing/wrong", so I assume everything is in it's right place.

![2023-02-11_21-59-33](https://user-images.githubusercontent.com/16250196/218281052-3152f812-64ea-432b-aa05-dddc5ad5d1ee.png)

Running server on windows, version 1.17.11

I get this error spammed in the server log, but only when there is a flue present:

```text
11.2.2023 22:00:51 [Fatal] System.IO.FileNotFoundException: Could not load file or assembly 'VSSurvivalMod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'VSSurvivalMod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at beehivekiln.blockentity.BlockEntityBeehiveKiln.onServerTick3s(Single dt)
   at beehivekiln.blockentity.BlockEntityBeehiveKiln.onServerTick1s(Single dt) in c:\Users\server\AppData\Roaming\VintagestoryData\Cache\unpack\beehivekiln_v1.2.1.zip_4eaad279077a\src\beehivekiln\blockentity\blockentitybeehivekiln.cs:line 148
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\EventManager.cs:line 106
   at Vintagestory.Server.CoreServerEventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerEventManager.cs:line 123
   at Vintagestory.Server.ServerMain.Process() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line 768

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

How do I fix this? Is there a dependency that I don't have?

**Comment by FalcoGer** [comment]
I have vintage story installed in a non default location. Maybe that's why it can't find the dll, it is definitely present in the installation directory in the /mods subdirectory. I tried making a Junktion to the server installation directory at %appdata%/Vintagestory but that didn't help.

**Comment by FalcoGer** [comment]
Just tested the mod in singleplayer (different computer, still windows 10, same mod pack) and that works fine. It's just the dedicated server that doesn't like me right now.

**Comment by FalcoGer** [comment]
Just tested on the server machine in singleplayer mode in the same world. It works as expected there as well. After that launched the dedicated server again, and it fails with the same error.

I'm not sure what else to do at this point.

**Comment by FalcoGer** [comment]
I have reinstalled the server to the default location and deleted the cache directory in VintagestoryData/cache. Problem persists.

**Comment by FalcoGer** [comment]
Enabled the log thing.

```text
12.2.2023 00:59:57 [Event] Falco [::ffff:192.168.1.11]:61724 joins.
12.2.2023 00:59:57 [Notification] A client reconnected, resuming game calendar.
12.2.2023 01:00:16 [Notification] Auto-sync thread running
12.2.2023 01:00:18 [Fatal] System.IO.FileNotFoundException: Could not load file or assembly 'VSSurvivalMod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'VSSurvivalMod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at beehivekiln.blockentity.BlockEntityBeehiveKiln.onServerTick3s(Single dt)
   at beehivekiln.blockentity.BlockEntityBeehiveKiln.onServerTick1s(Single dt) in c:\Users\server\AppData\Roaming\VintagestoryData\Cache\unpack\beehivekiln_v1.2.1.zip_4eaad279077a\src\beehivekiln\blockentity\blockentitybeehivekiln.cs:line 148
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\EventManager.cs:line 106
   at Vintagestory.Server.CoreServerEventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerEventManager.cs:line 123
   at Vintagestory.Server.ServerMain.Process() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line 768

=== Pre-bind state information ===
LOG: DisplayName = VSSurvivalMod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 (Fully-specified)
LOG: Appbase = file:///C:/Users/server/AppData/Roaming/Vintagestory/
LOG: Initial PrivatePath = NULL
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: No application configuration file found.
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///C:/Users/server/AppData/Roaming/Vintagestory/VSSurvivalMod.DLL.
LOG: Attempting download of new URL file:///C:/Users/server/AppData/Roaming/Vintagestory/VSSurvivalMod/VSSurvivalMod.DLL.
LOG: Attempting download of new URL file:///C:/Users/server/AppData/Roaming/Vintagestory/VSSurvivalMod.EXE.
LOG: Attempting download of new URL file:///C:/Users/server/AppData/Roaming/Vintagestory/VSSurvivalMod/VSSurvivalMod.EXE.

12.2.2023 01:00:20 [Fatal] System.IO.FileNotFoundException: Could not load file or assembly 'VSSurvivalMod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'VSSurvivalMod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at beehivekiln.blockentity.BlockEntityBeehiveKiln.onServerTick3s(Single dt)
   at beehivekiln.blockentity.BlockEntityBeehiveKiln.onServerTick1s(Single dt) in c:\Users\server\AppData\Roaming\VintagestoryData\Cache\unpack\beehivekiln_v1.2.1.zip_4eaad279077a\src\beehivekiln\blockentity\blockentitybeehivekiln.cs:line 148
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\EventManager.cs:line 106
   at Vintagestory.Server.CoreServerEventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerEventManager.cs:line 123
   at Vintagestory.Server.ServerMain.Process() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line 768

=== Pre-bind state information ===
LOG: DisplayName = VSSurvivalMod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 (Fully-specified)
LOG: Appbase = file:///C:/Users/server/AppData/Roaming/Vintagestory/
LOG: Initial PrivatePath = NULL
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: No application configuration file found.
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: The same bind was seen before, and was failed with hr = 0x80070002.

12.2.2023 01:00:24 [Notification] Last player disconnected, compacting large object heap...
12.2.2023 01:00:25 [Event] Player Falco left.
```

**Comment by FalcoGer** [comment]
The issue appears to be that it looks for the dll files in the wrong place.

Temporary workaround is to create symlinks to the DLLs in Mods in the vintage story directory.

Run cmd.exe as administrator and navigate into the VintageStory installation directory. Then run this:

```cmd
mklink VSCreativeMod.dll Mods\VSCreativeMod.dll
mklink VSEssentials.dll Mods\VSEssentials.dll
mklink VSSurvivalMod.dll Mods\VSSurvivalMod.dll
```

**Comment by FalcoGer** [comment]
Workaround does cause the flue to show the proper message (Temperature to low), but lighting a firepit doesn't actually raise the temperature. Breaking a block in the kiln and then rebuilding it updates the flue blockinfo to the ambient temperature, but it still doesn't raise with the fire.

Might be a separate bug. No error messages in the server log though.

**Comment by FalcoGer** [comment]
I compiled the DLL and placed into the mod zip file and removed the src folder from it. With the precompiled DLL it works properly.

**Comment by WickedSchnitzel** [comment]
> 

Could you upload the dll to the moddb?

**Comment by zach2039** [comment]
> > 
> 
> Could you upload the dll to the moddb?

New download for v1.18.5 [here](https://mods.vintagestory.at/download?fileid=11641), compiled version.
