### ISSUE TITLE
VS 1.18.15 Crash with Mod Version 1.5.0, 1.4.0

### ISSUE THREAD

**Issue by MorgansPeak** [zach2039/vs-beehivekiln#4]
<details> <summary>**Copying the error log to clipboard gave this;**</summary>

Running on 64 bit Windows with 16342 MB RAM
Game Version: v1.18.15 (Stable)
12/16/2023 8:14:06 PM: Critical error occurred
Loaded Mods: acorns@0.5.3, aculinaryartillery@1.0.15, bedrespawner@1.0.0, cellardoor@1.4.0, chiseltools@1.10.0, claycasting@1.1.1, decor@1.0.7, caninae@1.0.4, capreolinae@1.0.5, geodesandgemstones@1.1.0, hideandfabric@1.3.0, millwright@1.1.1, moremolds@1.4.2, nailsmold@1.0.1, nocharcoallost@1.0.0, OresAPlenty@3.1.0, pieontheshelf@1.0.0, potontheshelf@1.0.0, primitivesurvival@3.3.0, ragnamans-seeds-from-crops-recipes@1.0.0, bone2lime@1.0.2, game@1.18.15, alchemy@1.6.21, alloycalculator@1.0.0, ancienttools@1.5.11, betterfirepit@1.1.2, canjewelry@0.1.19, coinage@1.9.0, composter@1.1.0, electricity@0.0.10, expandedfoods@1.6.8, fromgoldencombs@1.4.25, hudclock@3.3.0, sailboat@1.2.4, medievalexpansion@3.11.1, morepiles@1.4.3, prospectorinfo@4.3.0, stickemup@1.1.0, stonebakeoven@1.1.1, storageoptions@1.0.1, useplanksinpitkiln@1.1.1, creative@1.18.15, survival@1.18.15, wildfarmingrevival@1.1.6, tradercamps@1.0.6, em@2.4.1, simplewinddirection@1.0.2, treetapping@1.0.0, xinvtweaks@1.5.7, bricklayers@2.4.0, coloredjugs@1.0.0
System.Exception: Don't know how to instantiate block of class 'BlockFirebrickKilnFlue' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateBlock(String blockClass) in VintagestoryLib\Common\ClassRegistry.cs:line 129
   at Vintagestory.Common.BlockTypeNet.ReadBlockTypePacket(Packet_BlockType packet, IWorldAccessor world, ClassRegistry registry) in VintagestoryLib\Common\Network\BlockTypeNet.cs:line 399
   at Vintagestory.Client.NoObf.ClientSystemStartup.PopulateBlocks(Block[] blocks, Int32 start, Int32 maxCount) in VintagestoryLib\Client\Systems\Startup.cs:line 546
   at Vintagestory.Client.NoObf.ClientSystemStartup.LoadBlockTypes() in VintagestoryLib\Client\Systems\Startup.cs:line 363
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1() in VintagestoryLib\Client\Systems\Startup.cs:line 338
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 108
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/16/2023 8:10:44 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER74DF.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7D8B.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7D9B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7DAB.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7DCB.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_05de85b5-a388-44fb-951a-b89d5a80cb56

Analysis symbol: 
Rechecking for solution: 0
Report Id: d0cc4704-455a-4271-8a50-425545b8c1f0
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
--------------
{ TimeGenerated = 12/16/2023 8:10:41 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0xbec
Faulting application start time: 0x01da309613496d94
Faulting application path: C:\Users\death\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\death\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: d0cc4704-455a-4271-8a50-425545b8c1f0
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 12/16/2023 8:10:29 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1801279755922800932, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: KERNELBASE.dll
P5: 10.0.19041.3086
P6: e1ac3f79
P7: e0434352
P8: 000000000002cf19
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3A66.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER42E3.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER42F4.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4301.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4322.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_1af71e27b9214b6bf8caa16ccc68e9e01a8a63_ee8069fc_5dbc2275-26d0-4612-8788-5d6e3000f442

Analysis symbol: 
Rechecking for solution: 0
Report Id: d4b9a1ca-454f-4492-a158-68869e9d5b3c
Report Status: 268566528
Hashed bucket: d32752c7c521349978ff6e64f8e18124
Cab Guid: 0 }` </details>

<details> <summary>**Client-main.txt included this;** </summary>

16.12.2023 20:14:06 [Fatal] Game Version: v1.18.15 (Stable)
12/16/2023 8:14:06 PM: Critical error occurred
Loaded Mods: acorns@0.5.3, aculinaryartillery@1.0.15, bedrespawner@1.0.0, cellardoor@1.4.0, chiseltools@1.10.0, claycasting@1.1.1, decor@1.0.7, caninae@1.0.4, capreolinae@1.0.5, geodesandgemstones@1.1.0, hideandfabric@1.3.0, millwright@1.1.1, moremolds@1.4.2, nailsmold@1.0.1, nocharcoallost@1.0.0, OresAPlenty@3.1.0, pieontheshelf@1.0.0, potontheshelf@1.0.0, primitivesurvival@3.3.0, ragnamans-seeds-from-crops-recipes@1.0.0, bone2lime@1.0.2, game@1.18.15, alchemy@1.6.21, alloycalculator@1.0.0, ancienttools@1.5.11, betterfirepit@1.1.2, canjewelry@0.1.19, coinage@1.9.0, composter@1.1.0, electricity@0.0.10, expandedfoods@1.6.8, fromgoldencombs@1.4.25, hudclock@3.3.0, sailboat@1.2.4, medievalexpansion@3.11.1, morepiles@1.4.3, prospectorinfo@4.3.0, stickemup@1.1.0, stonebakeoven@1.1.1, storageoptions@1.0.1, useplanksinpitkiln@1.1.1, creative@1.18.15, survival@1.18.15, wildfarmingrevival@1.1.6, tradercamps@1.0.6, em@2.4.1, simplewinddirection@1.0.2, treetapping@1.0.0, xinvtweaks@1.5.7, bricklayers@2.4.0, coloredjugs@1.0.0
System.Exception: Don't know how to instantiate block of class 'BlockFirebrickKilnFlue' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateBlock(String blockClass) in VintagestoryLib\Common\ClassRegistry.cs:line 129
   at Vintagestory.Common.BlockTypeNet.ReadBlockTypePacket(Packet_BlockType packet, IWorldAccessor world, ClassRegistry registry) in VintagestoryLib\Common\Network\BlockTypeNet.cs:line 399
   at Vintagestory.Client.NoObf.ClientSystemStartup.PopulateBlocks(Block[] blocks, Int32 start, Int32 maxCount) in VintagestoryLib\Client\Systems\Startup.cs:line 546
   at Vintagestory.Client.NoObf.ClientSystemStartup.LoadBlockTypes() in VintagestoryLib\Client\Systems\Startup.cs:line 363
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1() in VintagestoryLib\Client\Systems\Startup.cs:line 338
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 108
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Crash written to file at "C:\Users\death\AppData\Roaming\VintagestoryData\Logs\client-crash.txt"

16.12.2023 20:14:07 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
16.12.2023 20:16:19 [Fatal] The game probably cannot continue to launch.  There was a problem loading block and item shapes, it did not complete
16.12.2023 20:16:20 [Fatal] Game Version: v1.18.15 (Stable)
12/16/2023 8:16:20 PM: Critical error occurred
Loaded Mods: acorns@0.5.3, aculinaryartillery@1.0.15, bedrespawner@1.0.0, cellardoor@1.4.0, chiseltools@1.10.0, claycasting@1.1.1, decor@1.0.7, caninae@1.0.4, capreolinae@1.0.5, geodesandgemstones@1.1.0, hideandfabric@1.3.0, millwright@1.1.1, moremolds@1.4.2, nailsmold@1.0.1, nocharcoallost@1.0.0, OresAPlenty@3.1.0, pieontheshelf@1.0.0, potontheshelf@1.0.0, primitivesurvival@3.3.0, ragnamans-seeds-from-crops-recipes@1.0.0, bone2lime@1.0.2, game@1.18.15, alchemy@1.6.21, alloycalculator@1.0.0, ancienttools@1.5.11, betterfirepit@1.1.2, canjewelry@0.1.19, coinage@1.9.0, composter@1.1.0, electricity@0.0.10, expandedfoods@1.6.8, fromgoldencombs@1.4.25, hudclock@3.3.0, sailboat@1.2.4, medievalexpansion@3.11.1, morepiles@1.4.3, prospectorinfo@4.3.0, stickemup@1.1.0, stonebakeoven@1.1.1, storageoptions@1.0.1, useplanksinpitkiln@1.1.1, creative@1.18.15, survival@1.18.15, wildfarmingrevival@1.1.6, tradercamps@1.0.6, em@2.4.1, simplewinddirection@1.0.2, treetapping@1.0.0, xinvtweaks@1.5.7, bricklayers@2.4.0, coloredjugs@1.0.0
System.Exception: Something went wrong in the startup process, no item shapes have been loaded at all. Please try disabling all mods apart from Essentials, Survival, Creative. If that solves the issue, check which mod is causing this. If that does not solve the issue, please report.
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(String type, AssetLocation name, CompositeShape compositeShape, MeshData& modeldata, ITexPositionSource texSource, Int32 generalGlowLevel, Byte climateColorMapIndex, Byte seasonColorMapIndex, Nullable`1 quantityElements, String[] selectiveElements) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 115
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateItem(Item item, CompositeShape forShape, MeshData& modeldata) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 681
   at Vintagestory.Client.NoObf.ShapeTesselatorManager.TesselateItems(IList`1 itemtypes, Int32 offset, Int32 maxCount) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselatorManager.cs:line 859
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step7(Int32 index, Int32 frameCount) in VintagestoryLib\Client\Systems\Startup.cs:line 777
   at Vintagestory.Client.NoObf.ClientSystemStartup.<BeginItemTesselation>b__42_1() in VintagestoryLib\Client\Systems\Startup.cs:line 772
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 757
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 322
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Crash written to file at "C:\Users\death\AppData\Roaming\VintagestoryData\Logs\client-crash.txt"

16.12.2023 20:18:04 [Notification] Exiting game now. Server running=True. Exit reason: Game crashed </details>

<details> <summary> **Client-crash.txt included;** </summary>

Game Version: v1.18.15 (Stable)
12/16/2023 8:14:06 PM: Critical error occurred
Loaded Mods: acorns@0.5.3, aculinaryartillery@1.0.15, bedrespawner@1.0.0, cellardoor@1.4.0, chiseltools@1.10.0, claycasting@1.1.1, decor@1.0.7, caninae@1.0.4, capreolinae@1.0.5, geodesandgemstones@1.1.0, hideandfabric@1.3.0, millwright@1.1.1, moremolds@1.4.2, nailsmold@1.0.1, nocharcoallost@1.0.0, OresAPlenty@3.1.0, pieontheshelf@1.0.0, potontheshelf@1.0.0, primitivesurvival@3.3.0, ragnamans-seeds-from-crops-recipes@1.0.0, bone2lime@1.0.2, game@1.18.15, alchemy@1.6.21, alloycalculator@1.0.0, ancienttools@1.5.11, betterfirepit@1.1.2, canjewelry@0.1.19, coinage@1.9.0, composter@1.1.0, electricity@0.0.10, expandedfoods@1.6.8, fromgoldencombs@1.4.25, hudclock@3.3.0, sailboat@1.2.4, medievalexpansion@3.11.1, morepiles@1.4.3, prospectorinfo@4.3.0, stickemup@1.1.0, stonebakeoven@1.1.1, storageoptions@1.0.1, useplanksinpitkiln@1.1.1, creative@1.18.15, survival@1.18.15, wildfarmingrevival@1.1.6, tradercamps@1.0.6, em@2.4.1, simplewinddirection@1.0.2, treetapping@1.0.0, xinvtweaks@1.5.7, bricklayers@2.4.0, coloredjugs@1.0.0
System.Exception: Don't know how to instantiate block of class 'BlockFirebrickKilnFlue' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateBlock(String blockClass) in VintagestoryLib\Common\ClassRegistry.cs:line 129
   at Vintagestory.Common.BlockTypeNet.ReadBlockTypePacket(Packet_BlockType packet, IWorldAccessor world, ClassRegistry registry) in VintagestoryLib\Common\Network\BlockTypeNet.cs:line 399
   at Vintagestory.Client.NoObf.ClientSystemStartup.PopulateBlocks(Block[] blocks, Int32 start, Int32 maxCount) in VintagestoryLib\Client\Systems\Startup.cs:line 546
   at Vintagestory.Client.NoObf.ClientSystemStartup.LoadBlockTypes() in VintagestoryLib\Client\Systems\Startup.cs:line 363
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1() in VintagestoryLib\Client\Systems\Startup.cs:line 338
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 108
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Game Version: v1.18.15 (Stable)
12/16/2023 8:16:20 PM: Critical error occurred
Loaded Mods: acorns@0.5.3, aculinaryartillery@1.0.15, bedrespawner@1.0.0, cellardoor@1.4.0, chiseltools@1.10.0, claycasting@1.1.1, decor@1.0.7, caninae@1.0.4, capreolinae@1.0.5, geodesandgemstones@1.1.0, hideandfabric@1.3.0, millwright@1.1.1, moremolds@1.4.2, nailsmold@1.0.1, nocharcoallost@1.0.0, OresAPlenty@3.1.0, pieontheshelf@1.0.0, potontheshelf@1.0.0, primitivesurvival@3.3.0, ragnamans-seeds-from-crops-recipes@1.0.0, bone2lime@1.0.2, game@1.18.15, alchemy@1.6.21, alloycalculator@1.0.0, ancienttools@1.5.11, betterfirepit@1.1.2, canjewelry@0.1.19, coinage@1.9.0, composter@1.1.0, electricity@0.0.10, expandedfoods@1.6.8, fromgoldencombs@1.4.25, hudclock@3.3.0, sailboat@1.2.4, medievalexpansion@3.11.1, morepiles@1.4.3, prospectorinfo@4.3.0, stickemup@1.1.0, stonebakeoven@1.1.1, storageoptions@1.0.1, useplanksinpitkiln@1.1.1, creative@1.18.15, survival@1.18.15, wildfarmingrevival@1.1.6, tradercamps@1.0.6, em@2.4.1, simplewinddirection@1.0.2, treetapping@1.0.0, xinvtweaks@1.5.7, bricklayers@2.4.0, coloredjugs@1.0.0
System.Exception: Something went wrong in the startup process, no item shapes have been loaded at all. Please try disabling all mods apart from Essentials, Survival, Creative. If that solves the issue, check which mod is causing this. If that does not solve the issue, please report.
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(String type, AssetLocation name, CompositeShape compositeShape, MeshData& modeldata, ITexPositionSource texSource, Int32 generalGlowLevel, Byte climateColorMapIndex, Byte seasonColorMapIndex, Nullable`1 quantityElements, String[] selectiveElements) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 115
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateItem(Item item, CompositeShape forShape, MeshData& modeldata) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 681
   at Vintagestory.Client.NoObf.ShapeTesselatorManager.TesselateItems(IList`1 itemtypes, Int32 offset, Int32 maxCount) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselatorManager.cs:line 859
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step7(Int32 index, Int32 frameCount) in VintagestoryLib\Client\Systems\Startup.cs:line 777
   at Vintagestory.Client.NoObf.ClientSystemStartup.<BeginItemTesselation>b__42_1() in VintagestoryLib\Client\Systems\Startup.cs:line 772
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 757
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 322
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93 </details>

**Comment by MorgansPeak** [comment]
Edited because I didn't experience a crash with 1.5.1, but the grating and flue blocks were doing the white block with a red ? thing.

**Comment by zach2039** [comment]
Looks like beehivekiln mod isn't loaded in above logs. Is the mod installed properly? Was is installed with the one-click install feature of the mod db website?
